"""answers table added

Revision ID: bcdfcf55fcdc
Revises: a30a2b9e9e63
Create Date: 2019-12-04 11:28:53.148583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdfcf55fcdc'
down_revision = 'a30a2b9e9e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('date_answered', sa.DateTime(), nullable=True))
    op.add_column('question', sa.Column('date_asked', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'date_asked')
    op.drop_column('answer', 'date_answered')
    # ### end Alembic commands ###
